version: '3.8'

services:
  frontend:
    container_name: ubs-vac_frontend_1  # Renomeado para frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expondo a porta 80
    depends_on:
      - backend
    environment:
      - REACT_APP_API_HOST=http://localhost:8800  # Alterado para nome correto do backend
    networks:
      - app-network

  backend:
    container_name: ubs-vac_backend_1  # Renomeado para backend
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=faculdade
      - DB_NAME_LOGIN=login
      - DB_NAME_UBS=ubs
    ports:
      - "8800:8800"  # Expondo a porta 8800
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: faculdade
    ports:
      - "3306:3306"  # Usando a porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
