version: '3.8'

services:
  frontend:
    container_name: ubs-vac_backend_1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_HOST=http://ubs-vac_backend_1:8800
    networks:
      - app-network

  backend:
    container_name: ubs-vac_frontend_1
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=faculdade
      - DB_NAME_LOGIN=login  # Nome do banco de dados 'login'
      - DB_NAME_UBS=ubs      # Nome do banco de dados 'ubs'
    ports:
      - "8800:8800"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: faculdade  # Definir o nome do banco de dados inicial aqui
    ports:
      - "5070:5070"
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql  # Adicione o caminho para o script.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
