# version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_HOST=http://localhost:8800
    networks:
      - app-network
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_HOST=ubs-vac-db-1
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME_LOGIN=login  # Nome do banco de dados 'login'
      - DB_NAME_UBS=ubs      # Nome do banco de dados 'ubs'
    ports:
      - "8800:8800"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_INITDB_SKIP_TZINFO: 1  # Evita problemas com timezone
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network: